openapi: 3.0.0
servers:
  - url: http://filmy-19.herokuapp.com/api/v1
    description: Production server
  - url: http://localhost:8080/api/v1
    description: Local test server
info:
  title: Filmy
  version: 1.0.0
tags:
  - name: film
    description: all the  end points related to films
  - name: actor
    description: all the end points related to actor
  - name: user
    description: all the end points related to users
  - name: authentication
    description: all the end points related to authentication
  - name: docs
    description: all the end points related to docs
  - name: index
    description: all the end points related to index
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /film:
    get:
      tags:
        - film
      summary: get all film
      description: endpoint that is going do give back all the film saved in the database
      parameters:
        - in: query
          name: limitValue
          description: limit the number of results to a limit value
          required: false
          schema:
            type: integer
            minimum: 0
            example: 0
        - in: query
          name: offsetValue
          description: give an offsetValue value the results
          required: false
          schema:
            type: integer
            minimum: 0
            example: 0
      responses:
        200:
          description: status code OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    format: int32
                    example: 200
                  status_message:
                    type: string
                    example: Success
                  data:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 1
                        title:
                          type: string
                          example: "Spider-Man: Far from Home"
                        rating:
                          type: integer
                          format: int32
                          example: 76
                        release_date:
                          type: string
                          format: date
                          example: 2019-06-26
                        poster:
                          type: string
                          example: https://image.tmdb.org/t/p/w600_and_h900_bestv2/lcq8dVxeeOqHvvgcte707K0KVx5.jpg
                        actors:
                          type: array
                          items:
                            type: integer
                            format: int32
                            example: 1
        400:
          description: status code BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 400
                  status_message:
                    type: string
                    example: Invalid request message
                  error_message:
                    type: string
                    example: -20 is not a valid limit
        500:
          description: status code INTERNAL_SERVER_ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    format: int32
                    example: 500
                  status_message:
                    type: string
                    example: Internal server error
    post:
      tags:
        - film
      summary: add new film
      description: given the information about a new film the endpoint id going to add the film in the database
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  example: john wick
                rating:
                  type: integer
                  format: int32
                  example: 80
                release_date:
                  type: string
                  format: date
                  example: 2019-10-10
                poster:
                  type: string
                  example: https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg
      responses:
        201:
          description: status code OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    format: int32
                    example: 201
                  status_message:
                    type: string
                    example: Resource created
                  data:
                    type: object
                    properties:
                      title:
                        type: string
                        example: blax
                      rating:
                        type: integer
                        format: int32
                        example: 10
                      release_date:
                        type: string
                        format: date
                        example: 2019-10-10
                      poster:
                        type: string
                        example: https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg
                      id:
                        type: integer
                        format: int32
                        example: 6
                      create_date:
                        type: string
                        example: 2019-11-29T14:31:30.669Z
                      update_date:
                        type: string
                        example: 2019-11-29T14:31:30.669Z
        400:
          description: status code BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 400
                  status_message:
                    type: string
                    example: Invalid request message
                  error_message:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                          example: bello
                        property:
                          type: string
                          example: poster
                        constraints:
                          type: object
                          properties:
                            isUrl:
                              type: string
                              example: poster must be an URL address
        401:
          description: status code UNAUTHORIZED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 401
                  status_message:
                    type: string
                    example: Unauthorized request
                  error_message:
                    type: string
                    example: Invalid Authorization Token
        #magari anche 500
  /film/{filmID}:
    get:
      tags:
        - film
      summary: get film by id
      description: endpoint that is going do give back all the information about a specific film given the id
      parameters:
        - in: path
          name: filmID
          description: give the id of the film that you want
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: status code OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status_code:
                    type: integer
                    format: int32
                    example: 200
                  status_message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int32
                        example: 1
                      title:
                        type: string
                        example: "Spider-Man: Far from Home"
                      rating:
                        type: integer
                        format: int32
                        example: 76
                      release_date:
                        type: string
                        format: date
                        example: 2019-06-26
                      poster:
                        type: string
                        example: https://image.tmdb.org/t/p/w600_and_h900_bestv2/lcq8dVxeeOqHvvgcte707K0KVx5.jpg
                      actors:
                        type: array
                        items:
                          type: integer
                          format: int32
                          example: 1
        404:
          description: status code NOT_FOUND
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status_code:
                    type: integer
                    format: int32
                    example: 404
                  status_message:
                    type: string
                    example: Resource not found
                  error_message:
                    type: string
                    example: Unable to find a Film with id 1
    put:
      tags:
        - film
      summary: upadete film by id
      description: endpoint that let you modify a specific film
      parameters:
        - in: path
          name: filmID
          description: give the id of the film that you want to modify
          required: true
          schema:
            type: integer
            example: 1
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  example: john wick
                rating:
                  type: integer
                  format: int32
                  example: 80
                release_date:
                  type: string
                  format: date
                  example: 2019-10-10
                poster:
                  type: string
                  example: https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg
      responses:
        202:
          description: status code ACCEPTED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 200
                  status_message:
                    type: string
                    example: Success
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int32
                        example: 4
                      title:
                        type: string
                        example: John Wick 2
                      rating:
                        type: integer
                        format: int32
                        example: 80
                      release_date:
                        type: string
                        example: 2019-10-10T00:00:00.000Z
                      poster:
                        type: string
                        example: https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.png
                      update_date:
                        type: string
                        example: 2019-11-30T15:14:17.319Z
        400: #da modificare
          description: status code BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 400
                  status_message:
                    type: string
                    example: Invalid request message
                  error_message:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                          example: bello
                        property:
                          type: string
                          example: poster
                        constraints:
                          type: object
                          properties:
                            isUrl:
                              type: string
                              example: poster must be an URL address
        401:
          description: status code UNAUTHORIZED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 401
                  status_message:
                    type: string
                    example: Unauthorized request
                  error_message:
                    type: string
                    example: Invalid Authorization Token
        #magari anche 500
    delete:
      tags:
        - film
      summary: delete film by id
      description: endpoint that let you delete a specific film
      parameters:
        - in: path
          name: filmID
          description: give the id of the film that you want to delete
          required: true
          schema:
            type: integer
            example: 1
      security:
        - bearerAuth: []
      responses:
        202:
          description: status code ACCEPTED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 202
                  status_message:
                    type: string
                    example: Request accepted
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int32
                        example: 6
                      title:
                        type: string
                        example: John Wick 2
                      rating:
                        type: integer
                        format: int32
                        example: 80
                      release_date:
                        type: string
                        format: date
                        example: 2019-10-10
                      poster:
                        type: string
                        example: https://upload.wikimedia.org/wikipedia/en/9/98/John_Wick_TeaserPoster.jpg
        400: #da modificare
          description: status code BAD_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 400
                  status_message:
                    type: string
                    example: Invalid request message
                  error_message:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                          example: bello
                        property:
                          type: string
                          example: poster
                        constraints:
                          type: object
                          properties:
                            isUrl:
                              type: string
                              example: poster must be an URL address
        401:
          description: status code UNAUTHORIZED
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
                    format: int32
                    example: 401
                  status_message:
                    type: string
                    example: Unauthorized request
                  error_message:
                    type: string
                    example: Invalid Authorization Token
        #magari anche 500
